name: Build PyTorch Wheels

on:
  workflow_call:
    inputs:
      families:
        required: true
        type: string
      python_version:
        required: true
        type: string
      find_links:
        required: true
        type: string
      version_suffix:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_pytorch_wheels:
    name: ${{ inputs.families }} | Python ${{ inputs.python_version }}
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64:main
    env:
      OUTPUT_DIR: /__w/TheRock/TheRock/output
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Confirm Container Environment
        run: |
          echo "Hostname: $(hostname)"
          echo "Current User: $(whoami)"
          echo "Container ID (if any):"
          cat /proc/self/cgroup | grep 'docker\|kubepods\|containerd' || echo "No container ID found"
          echo "Listing files in /opt/python to verify manylinux presence:"
          ls -lh /opt/python

      - name: Build PyTorch Wheels
        run: |
          PY_VER="${{ inputs.python_version }}"
          PY_TAG="cp${PY_VER//./}-cp${PY_VER//./}"
          PYTHON_BIN="/opt/python/${PY_TAG}/bin/python"

          echo "Using Python: $PYTHON_BIN"

          $PYTHON_BIN ./external-builds/pytorch/build_prod_wheels.py  build \
            --install-rocm \
            --clean \
            --output-dir ${{ env.OUTPUT_DIR }}/packages/dist \
            --pytorch-rocm-arch ${{ inputs.families }} \
            --find-links "https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/index.html" \
            --version-suffix "+rocmsdk${{ inputs.version_suffix }}"

      - name: Upload wheels to S3
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          aws s3 cp ${{ env.OUTPUT_DIR }}/packages/dist/ s3://therock-nightly-python/${{ inputs.families }}/ \
            --recursive --exclude "*" --include "*.whl"

      - name: List files in S3 (Debug)
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          aws s3 ls s3://therock-nightly-python/${{ inputs.families }}/ --recursive

      - name: Dump Torch S3 index (debug)
        run: |
          echo "Fetching index from: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/index.html"
          curl -s "https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/index.html"

      - name: Test Installed Wheel
        run: |
          PY_VER="${{ inputs.python_version }}"
          PY_TAG="cp${PY_VER//./}-cp${PY_VER//./}"
          PYTHON_BIN="/opt/python/${PY_TAG}/bin/python"

          echo "Using $PYTHON_BIN to test installed wheel..."

          echo "Installing torch from: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/index.html"
          $PYTHON_BIN -m pip install --no-cache-dir --no-index \
            --find-links="https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/index.html" \
            torch

          echo "Checking if torch is importable:"
          $PYTHON_BIN -c "import torch; print(f'torch version: {torch.__version__}')"

          bash external-builds/pytorch/smoke-tests/run_smoke_tests.sh

      - name: Show S3 index.html (debug)
        run: |
          curl -s "https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/index.html"