name: Build PyTorch Wheels

on:
  workflow_call:
    inputs:
      families:
        required: true
        type: string
      python_version:
        required: true
        type: string
      find_links:
        required: true
        type: string
      version_suffix:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_pytorch_wheels:
    name: ${{ inputs.families }} | Python ${{ inputs.python_version }}
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64:main
    env:
      OUTPUT_DIR: /__w/TheRock/TheRock/output
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PyTorch Wheels
        run: |
          CLEAN_PY="${{ inputs.python_version }}"
          PY_NO_DOTS="${CLEAN_PY//./}"
          PYTHON_BIN="/opt/python/cp${PY_NO_DOTS}-cp${PY_NO_DOTS}/bin/python3"

          $PYTHON_BIN ./build_tools/torch/build_prod_wheels.py build \
            --install-rocm \
            --clean \
            --output-dir ${{ env.OUTPUT_DIR }}/packages/dist \
            --pytorch-rocm-arch ${{ inputs.families }} \
            --find-links "${{ inputs.find_links }}" \
            --version-suffix "+rocmsdk${{ inputs.version_suffix }}"

      - name: Upload wheels to S3
        if: ${{ github.repository_owner == 'ROCm' }}
        run: |
          aws s3 cp ${{ env.OUTPUT_DIR }}/packages/dist/ s3://therock-nightly-python/${{ inputs.families }}/ \
            --recursive --exclude "*" --include "*.whl"

      - name: Test Installed Wheel
        run: |
          PYTHON_BIN="/opt/python/cp${{ inputs.python_version//./ }}-cp${{ inputs.python_version//./ }}/bin/python"
          $PYTHON_BIN -m pip install --no-cache-dir \
            --find-links=https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.families }}/ \
            torch
          $PYTHON_BIN build_tools/torch/test_installed_torch.py
