name: Release PyTorch Wheels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_pytorch_grid:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12"]
        target: [gfx942]
    uses: ./.github/workflows/build_pytorch_wheels.yml
    with:
      target: ${{ matrix.target }}
      python_version: ${{ matrix.python_version }}
      family: gfx94X-dcgpu
      find_links: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.family }}/index.html
      version_suffix: "20250528"