name: Release Linux PyTorch Wheels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version_suffix: ${{ steps.set.outputs.version_suffix }}
    steps:
      - id: set
        run: echo "version_suffix=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  release_pytorch:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.11", "3.12"]
        target: [gfx942]
    uses: ./.github/workflows/build_pytorch_wheels.yml
    with:
      family: gfx94X-dcgpu
      python_version: ${{ matrix.python_version }}
      target: ${{ matrix.target }}
      find_links: https://therock-nightly-python.s3.us-east-2.amazonaws.com/${{ inputs.family }}/index.html
      version_suffix: ${{ needs.setup.outputs.version_suffix }}
